import React from 'react';
import { MenuTab, MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // Tiffin
  {
    id: 't1',
    title: 'Standard Daily Tiffin',
    price: '₹120/meal',
    numericPrice: 120,
    description: 'Complete balanced North Indian meal with 4 Rotis, Rice, Dal, Sabzi & Raita. Freshly prepared every day.',
    category: MenuTab.TIFFIN,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 't2',
    title: 'Premium Corporate Meal',
    price: '₹180/meal',
    numericPrice: 180,
    description: 'Enhanced menu featuring exotic seasonal veg, Paneer, Premium Basmati & a traditional sweet.',
    category: MenuTab.TIFFIN,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 't3',
    title: 'Non-Veg Tiffin',
    price: '₹200/meal',
    numericPrice: 200,
    description: 'Hearty tiffin with Chicken Curry, 4 Rotis, Rice, Dal & fresh Salad.',
    category: MenuTab.TIFFIN,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=600',
    isVeg: false,
  },

  // Breakfast
  {
    id: 'b1',
    title: 'Aloo Paratha',
    price: '₹60/plate',
    numericPrice: 60,
    description: 'Golden, crispy whole wheat parathas stuffed with spiced mashed potatoes. Served with butter and pickle.',
    category: MenuTab.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 'b2',
    title: 'Poha with Jalebi',
    price: '₹50/plate',
    numericPrice: 50,
    description: 'Light & fluffy flattened rice cooked with onions and spices, served with crispy hot jalebis.',
    category: MenuTab.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce70?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 'b3',
    title: 'Idli Sambar',
    price: '₹55/plate',
    numericPrice: 55,
    description: 'Soft steamed rice cakes served with tangy lentil sambar and fresh coconut chutney.',
    category: MenuTab.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 'b4',
    title: 'Bread Omelette',
    price: '₹70/plate',
    numericPrice: 70,
    description: 'Fluffy spiced eggs cooked with peppers and onions, served with buttered toast.',
    category: MenuTab.BREAKFAST,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=600',
    isVeg: false,
  },

  // Lunch
  {
    id: 'l1',
    title: 'Dal Tadka with Rice',
    price: '₹90/plate',
    numericPrice: 90,
    description: 'Slow-cooked yellow lentils tempered with cumin, garlic & dried red chillies. Served with steamed rice.',
    category: MenuTab.LUNCH,
    image: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 'l2',
    title: 'Paneer Butter Masala',
    price: '₹150/plate',
    numericPrice: 150,
    description: 'Creamy tomato-based gravy with soft paneer cubes. Served with 3 Butter Rotis.',
    category: MenuTab.LUNCH,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 'l3',
    title: 'Chicken Biryani',
    price: '₹180/plate',
    numericPrice: 180,
    description: 'Aromatic long-grain basmati rice layered with tender chicken, saffron, and whole spices. Served with raita.',
    category: MenuTab.LUNCH,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=600',
    isVeg: false,
  },
  {
    id: 'l4',
    title: 'Chole Bhature',
    price: '₹100/plate',
    numericPrice: 100,
    description: 'Spiced chickpea curry served with two fluffy deep-fried bhaturas. A classic North Indian combo.',
    category: MenuTab.LUNCH,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },

  // Dinner
  {
    id: 'd1',
    title: 'Roti Sabzi Combo',
    price: '₹100/plate',
    numericPrice: 100,
    description: '4 fresh rotis with a seasonal sabzi and a bowl of dal. Light and wholesome dinner.',
    category: MenuTab.DINNER,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 'd2',
    title: 'Butter Chicken',
    price: '₹200/plate',
    numericPrice: 200,
    description: 'Tender chicken in a rich, velvety tomato-cream sauce. Best served with buttered naan.',
    category: MenuTab.DINNER,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=600',
    isVeg: false,
  },
  {
    id: 'd3',
    title: 'Rajma Chawal',
    price: '₹110/plate',
    numericPrice: 110,
    description: 'Classic kidney bean curry cooked in a thick tomato-onion gravy. Served with steamed white rice.',
    category: MenuTab.DINNER,
    image: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 'd4',
    title: 'Mutton Curry',
    price: '₹250/plate',
    numericPrice: 250,
    description: 'Slow-cooked tender mutton in a robust spiced onion-tomato gravy. Served with 4 rotis.',
    category: MenuTab.DINNER,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=600',
    isVeg: false,
  },

  // Sweets
  {
    id: 's1',
    title: 'Traditional Thekua',
    price: '₹180/500g',
    numericPrice: 180,
    description: 'Iconic wheat and jaggery cookies, handcrafted with love. A Bihar delicacy.',
    category: MenuTab.SWEETS,
    image: 'https://images.unsplash.com/photo-1582298538104-fe2e74c27f59?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 's2',
    title: 'Gulab Jamun',
    price: '₹80/6 pcs',
    numericPrice: 80,
    description: 'Soft milk-solid dumplings soaked in rose-flavored sugar syrup. Served warm.',
    category: MenuTab.SWEETS,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
  {
    id: 's3',
    title: 'Kheer',
    price: '₹90/bowl',
    numericPrice: 90,
    description: 'Creamy rice pudding slow-cooked in full-fat milk, sweetened with sugar and cardamom.',
    category: MenuTab.SWEETS,
    image: 'https://images.unsplash.com/photo-1602351447937-745cb720612f?auto=format&fit=crop&q=80&w=600',
    isVeg: true,
  },
];

export const CHEF_EXPERTISE = [
  { label: 'Indian Cuisine', value: 95 },
  { label: 'Flavor Fusion', value: 85 },
  { label: 'Traditional Baking', value: 80 },
];
